import { db } from "./firebase-init.js";
import { doc, onSnapshot, collection, getDocs } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const DEFAULTS={home:{bgStyle:"aurora",bgOverlay:55,bgMotion:true},store:{bgStyle:"grid",bgOverlay:62,bgMotion:true},custom:{bgStyle:"cinematic",bgOverlay:58,bgMotion:true},art:{bgStyle:"particles",bgOverlay:60,bgMotion:true},novita:{bgStyle:"aurora",bgOverlay:62,bgMotion:true},forum:{bgStyle:"grid",bgOverlay:68,bgMotion:true},team:{bgStyle:"cinematic",bgOverlay:60,bgMotion:true},recensioni:{bgStyle:"aurora",bgOverlay:62,bgMotion:true},contatti:{bgStyle:"cinematic",bgOverlay:60,bgMotion:true},faq:{bgStyle:"grid",bgOverlay:70,bgMotion:true},login:{bgStyle:"aurora",bgOverlay:70,bgMotion:true},register:{bgStyle:"aurora",bgOverlay:70,bgMotion:true},dashboard:{bgStyle:"none",bgOverlay:72,bgMotion:false}};
const PRESETS={midnight:{label:"Midnight Luxe",style:"none",overlay:64,motion:false,colors:["#05070e","#121a2a"]},violet:{label:"Violet Aurora",style:"aurora",overlay:54,motion:true,colors:["#31145d","#0a1d38"]},cyber:{label:"Cyber Grid",style:"grid",overlay:66,motion:true,colors:["#082530","#17103b"]},chrome:{label:"Liquid Chrome",style:"cinematic",overlay:60,motion:true,colors:["#30264b","#071828"]},workshop:{label:"Warm Workshop",style:"aurora",overlay:58,motion:false,colors:["#432534","#16121d"]},minimal:{label:"Minimal Black",style:"none",overlay:72,motion:false,colors:["#08090d","#161922"]}};
const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;let key=document.body.dataset.page||"home",unsub=()=>{},stop=()=>{};
function url(v=""){v=String(v||"").trim();if(v.startsWith("//"))v="https:"+v;if(v.startsWith("http://"))v="https://"+v.slice(7);return v}
function shell(){let e=document.querySelector("#page-bg");if(e)return e;e=document.createElement("div");e.id="page-bg";e.className="page-bg";e.setAttribute("aria-hidden","true");e.innerHTML='<div class="page-bg__layer page-bg__media"></div><div class="page-bg__layer page-bg__fx"></div><div class="page-bg__overlay"></div><div class="page-bg__vignette"></div>';document.documentElement.prepend(e);document.body.classList.add("has-page-bg");return e}
function paint(root,c){const media=root.querySelector(".page-bg__media"),fx=root.querySelector(".page-bg__fx"),overlay=root.querySelector(".page-bg__overlay"),image=url(c.bgImageUrl),video=url(c.bgVideoUrl),o=Math.max(0,Math.min(85,Number(c.bgOverlay??55)))/100;media.innerHTML="";fx.innerHTML="";if(video){const v=document.createElement("video");v.src=video;v.autoplay=v.muted=v.loop=v.playsInline=true;v.setAttribute("muted","");media.append(v);v.play().catch(()=>{})}else if(image){const i=document.createElement("div");i.className="page-bg__photo";i.style.backgroundImage=`url("${image.replace(/"/g,"%22")}")`;media.append(i)}const s=c.bgStyle||"none";if(s!=="none"){fx.className="page-bg__layer page-bg__fx page-bg__fx--"+s;fx.innerHTML=s==="particles"?'<span class="bg-dot"></span><span class="bg-dot"></span><span class="bg-dot"></span>':""}overlay.style.background=`linear-gradient(135deg,rgba(4,6,13,${Math.min(.9,o+.15)}),rgba(5,7,14,${o}))`;root.dataset.style=s;stop();if(c.bgMotion!==false&&!reduce){let x=0,y=0,tx=0,ty=0,raf;const move=e=>{tx=(e.clientX/innerWidth-.5)*2;ty=(e.clientY/innerHeight-.5)*2};addEventListener("pointermove",move,{passive:true});const tick=()=>{x+=(tx-x)*.04;y+=(ty-y)*.04;media.style.transform=`translate3d(${x*-12}px,${y*-8}px,0) scale(1.04)`;fx.style.transform=`translate3d(${x*-7}px,${y*-6}px,0)`;raf=requestAnimationFrame(tick)};tick();stop=()=>{cancelAnimationFrame(raf);removeEventListener("pointermove",move)}}}
function cache(c){try{const a=JSON.parse(localStorage.gr_bgs||"{}");a[key]={image:c.bgImageUrl||"",video:c.bgVideoUrl||"",style:c.bgStyle,overlay:c.bgOverlay,motion:c.bgMotion};localStorage.gr_bgs=JSON.stringify(a)}catch(_){}}
function apply(c){paint(shell(),c);cache(c)}
function listen(){unsub();const fallback=DEFAULTS[key]||DEFAULTS.home;unsub=onSnapshot(doc(db,"siteContent",key),s=>{const d=s.exists()?s.data():{};apply({bgImageUrl:d.bgImageUrl||"",bgVideoUrl:d.bgVideoUrl||"",bgStyle:d.bgStyle||fallback.bgStyle,bgOverlay:d.bgOverlay??fallback.bgOverlay,bgMotion:d.bgMotion!==false})},()=>apply(fallback))}
function css(){if(document.querySelector("#gr-bg-preset-css"))return;const s=document.createElement("style");s.id="gr-bg-preset-css";s.textContent=`.page-bg{position:fixed;inset:0;z-index:-1;overflow:hidden;background:#070912}.page-bg__layer,.page-bg__overlay,.page-bg__vignette{position:absolute;inset:-4%;pointer-events:none}.page-bg__media{background:#080b14 center/cover no-repeat}.page-bg__media video,.page-bg__photo{width:100%;height:100%;object-fit:cover;background:center/cover}.page-bg__overlay{z-index:2}.page-bg__fx{z-index:1}.page-bg__fx--aurora,.page-bg__fx--cinematic{background:radial-gradient(circle at 20% 15%,#8b3dff66,transparent 35%),radial-gradient(circle at 80% 70%,#1bcfff44,transparent 40%);filter:blur(22px)}.page-bg__fx--grid,.page-bg__fx--cinematic{background-image:linear-gradient(#7c5cff20 1px,transparent 1px),linear-gradient(90deg,#7c5cff20 1px,transparent 1px);background-size:42px 42px}.page-bg__fx--particles .bg-dot{position:absolute;width:4px;height:4px;border-radius:50%;background:#d8ffff;box-shadow:0 0 18px #9b3dff}.bg-dot:nth-child(1){left:16%;top:25%}.bg-dot:nth-child(2){left:72%;top:55%}.bg-dot:nth-child(3){left:48%;top:80%}.bg-preset-preview{height:92px;border-radius:12px;margin:0 0 14px;border:1px solid #ffffff1c;background:linear-gradient(135deg,#31145d,#0a1d38);box-shadow:inset 0 0 30px #0008}`;document.head.append(s)}
function enhanceDashboard(){if(key!=="dashboard")return;const form=document.querySelector("#bg-form"),style=form?.querySelector("#bg-style");if(!form||!style||document.querySelector("#bg-preset"))return;const field=document.createElement("div");field.className="field";field.innerHTML='<label for="bg-preset">Preset Gaming Relax</label><select id="bg-preset"><option value="">Personalizzato</option>'+Object.entries(PRESETS).map(([id,p])=>`<option value="${id}">${p.label}</option>`).join("")+'</select><div class="bg-preset-preview" id="bg-preset-preview"></div><p class="file-status">Il preset imposta stile, leggibilità e movimento. Immagine e video non vengono modificati.</p>';style.closest(".field").before(field);const sel=field.querySelector("select"),preview=field.querySelector("div");const update=()=>{const p=PRESETS[sel.value]||PRESETS.violet;preview.style.background=`linear-gradient(135deg,${p.colors[0]},${p.colors[1]})`};sel.addEventListener("change",()=>{const p=PRESETS[sel.value];if(!p)return;style.value=p.style;const o=form.querySelector("#bg-overlay");o.value=p.overlay;o.dispatchEvent(new Event("input"));form.querySelector("#bg-motion").checked=p.motion;update()});update()}
css();listen();enhanceDashboard();addEventListener("gr:navigated",()=>{key=document.body.dataset.page||"home";listen();enhanceDashboard()});getDocs(collection(db,"siteContent")).then(s=>{try{const a=JSON.parse(localStorage.gr_bgs||"{}");s.forEach(x=>{const d=x.data();a[x.id]={image:d.bgImageUrl||"",video:d.bgVideoUrl||"",style:d.bgStyle||"",overlay:d.bgOverlay,motion:d.bgMotion}});localStorage.gr_bgs=JSON.stringify(a)}catch(_){}}).catch(()=>{});
